name: Build AXP223 Tools (read/write) statically for ARMv7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt update && sudo apt install -y musl-tools gcc-arm-linux-gnueabihf

    - name: Compile tools
      run: |
        arm-linux-gnueabihf-gcc -static -o i2cread_axp i2cread_axp.c
        arm-linux-gnueabihf-gcc -static -o i2cset_axp i2cset_axp.c
        arm-linux-gnueabihf-gcc -static -o i2cset_axp i2cread_axp_full.c
        zip axp223-tools-armv7.zip i2cread_axp i2cset_axp i2cread_axp_full

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: axp223-tools
        path: axp223-tools-armv7.zip
