name: Build i2cread tool for ARMv7 (static)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y musl-tools gcc-arm-linux-gnueabihf

    - name: Build statically linked i2cread
      run: |
        arm-linux-gnueabihf-gcc -static -o i2cread i2cread.c
        zip i2cread-armv7.zip i2cread

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: i2cread-armv7
        path: i2cread-armv7.zip
